### PR TITLE
implements monitoring role

### PR DESCRIPTION
**Pull request by giovannimirarchi420**

### CODE REVIEW

**Comment by frisso** [comment]
@giovannimirarchi420 This looks good to me!
Two changes requested:
- write in English
- Change the "Monitor" role in "Energy monitoring" (e.g., "energymon" role), given that we're targeting that software.

**Comment by giovannimirarchi420** [comment]
@frisso I have made the requested changes.
The role has now been renamed to 'energymon', as suggested.
Additionally, I have included a new section in the README.md file that explains how to reinstall a specific component.

Thanks,
Giovanni

**Review by frisso — APPROVED** [review]

**Comment by frisso** [comment]
This looks good to me. @andreacv98 @fracappa Please proceed the way you feel better (either ask for modifications, or merge). Thanks!

**Comment by fracappa** [comment]
Merged.
Thanks @giovannimirarchi420 !

**Pull request merged**
